analytics: {}
color:
  brandColors:
    - '#3D3D3D'
    - '#3D3D3D'
  brandStrength: 0.518018
  lightness: 0.733108
  rhythmicContrast: 0.612612
  saturation: 0.443693
cta: {}
layout_spectrum: 0.353603
name: Low_res
opengraph: {}
purpose: []
typography_spectrum: 0.456081
