name: Low_res
favicon: null
layout_spectrum: 0.7723429459147155
typography_spectrum: 0.5068370522931218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.46443286119028926
  lightness: 0.8441234629135579
  saturation: 0.5430470425635576
  rhythmicContrast: 0.33437379682436585
purpose: []
