analytics: {}
color:
  brandColors:
    - '#3D3D3D'
    - '#3D3D3D'
  brandStrength: 0.679054
  lightness: 0.829955
  rhythmicContrast: 0.612612
  saturation: 0.327702
cta: {}
layout_spectrum: 0.174549
name: Low_res
opengraph: {}
purpose: []
typography_spectrum: 0.456081
